// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_regression_model_xptr
SEXP build_regression_model_xptr(Eigen::VectorXd y, Eigen::MatrixXd X, double lambda2, double a, double b);
RcppExport SEXP _hmcx_build_regression_model_xptr(SEXP ySEXP, SEXP XSEXP, SEXP lambda2SEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(build_regression_model_xptr(y, X, lambda2, a, b));
    return rcpp_result_gen;
END_RCPP
}
// build_regression_model_cppad_xptr
SEXP build_regression_model_cppad_xptr(Eigen::VectorXd theta_init, Eigen::VectorXd y, Eigen::MatrixXd X, double lambda2, double a, double b);
RcppExport SEXP _hmcx_build_regression_model_cppad_xptr(SEXP theta_initSEXP, SEXP ySEXP, SEXP XSEXP, SEXP lambda2SEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(build_regression_model_cppad_xptr(theta_init, y, X, lambda2, a, b));
    return rcpp_result_gen;
END_RCPP
}
// build_ddm4_cppad_xptr
SEXP build_ddm4_cppad_xptr(Eigen::VectorXd theta_init, Eigen::VectorXd rts, Eigen::VectorXd xs, Eigen::VectorXd muPrior_sp, Eigen::VectorXd sdPrior_sp, double min_rt, double s2, int kmax);
RcppExport SEXP _hmcx_build_ddm4_cppad_xptr(SEXP theta_initSEXP, SEXP rtsSEXP, SEXP xsSEXP, SEXP muPrior_spSEXP, SEXP sdPrior_spSEXP, SEXP min_rtSEXP, SEXP s2SEXP, SEXP kmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type muPrior_sp(muPrior_spSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type sdPrior_sp(sdPrior_spSEXP);
    Rcpp::traits::input_parameter< double >::type min_rt(min_rtSEXP);
    Rcpp::traits::input_parameter< double >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< int >::type kmax(kmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(build_ddm4_cppad_xptr(theta_init, rts, xs, muPrior_sp, sdPrior_sp, min_rt, s2, kmax));
    return rcpp_result_gen;
END_RCPP
}
// evaluate_model_ptr
Rcpp::List evaluate_model_ptr(Eigen::VectorXd theta, SEXP model_ptr);
RcppExport SEXP _hmcx_evaluate_model_ptr(SEXP thetaSEXP, SEXP model_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(evaluate_model_ptr(theta, model_ptr));
    return rcpp_result_gen;
END_RCPP
}
// find_reasonable_epsilon_cpp
double find_reasonable_epsilon_cpp(Eigen::VectorXd theta, SEXP model_ptr, Eigen::VectorXd M, Eigen::VectorXd invM);
RcppExport SEXP _hmcx_find_reasonable_epsilon_cpp(SEXP thetaSEXP, SEXP model_ptrSEXP, SEXP MSEXP, SEXP invMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type M(MSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type invM(invMSEXP);
    rcpp_result_gen = Rcpp::wrap(find_reasonable_epsilon_cpp(theta, model_ptr, M, invM));
    return rcpp_result_gen;
END_RCPP
}
// hmcstep_cpp
Rcpp::List hmcstep_cpp(Eigen::VectorXd theta, SEXP model_ptr, Eigen::VectorXd M, Eigen::VectorXd invM, double epsilon, int L);
RcppExport SEXP _hmcx_hmcstep_cpp(SEXP thetaSEXP, SEXP model_ptrSEXP, SEXP MSEXP, SEXP invMSEXP, SEXP epsilonSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type M(MSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type invM(invMSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(hmcstep_cpp(theta, model_ptr, M, invM, epsilon, L));
    return rcpp_result_gen;
END_RCPP
}
// nutstep_cpp
Rcpp::List nutstep_cpp(Eigen::VectorXd theta, SEXP model_ptr, Eigen::VectorXd M, Eigen::VectorXd invM, double epsilon, int max_depth);
RcppExport SEXP _hmcx_nutstep_cpp(SEXP thetaSEXP, SEXP model_ptrSEXP, SEXP MSEXP, SEXP invMSEXP, SEXP epsilonSEXP, SEXP max_depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type M(MSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type invM(invMSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    rcpp_result_gen = Rcpp::wrap(nutstep_cpp(theta, model_ptr, M, invM, epsilon, max_depth));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hmcx_build_regression_model_xptr", (DL_FUNC) &_hmcx_build_regression_model_xptr, 5},
    {"_hmcx_build_regression_model_cppad_xptr", (DL_FUNC) &_hmcx_build_regression_model_cppad_xptr, 6},
    {"_hmcx_build_ddm4_cppad_xptr", (DL_FUNC) &_hmcx_build_ddm4_cppad_xptr, 8},
    {"_hmcx_evaluate_model_ptr", (DL_FUNC) &_hmcx_evaluate_model_ptr, 2},
    {"_hmcx_find_reasonable_epsilon_cpp", (DL_FUNC) &_hmcx_find_reasonable_epsilon_cpp, 4},
    {"_hmcx_hmcstep_cpp", (DL_FUNC) &_hmcx_hmcstep_cpp, 6},
    {"_hmcx_nutstep_cpp", (DL_FUNC) &_hmcx_nutstep_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_hmcx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
